version: 1.0
jobs:
  build_and_tests_back:
    docker:
      - image: cimg/node:21.4.0
    working_directory: ../backend
    steps:
      - checkout
      - run: npm i
      - run: npm run db-install
      - run: npm run lint-check
      - run: npm run type-check
      - run: npm run unit-tests

  build_and_tests_front:
    docker:
      - image: cimg/node:21.4.0
    working_directory: ../frontend
    steps:
      - checkout
      - run: npm i
      - run: npm run lint-check
      - run: npm run type-check
      - run: npm run unit-tests

workflows:
  build_and_test-back:
    jobs:
      - build_and_tests_back
      - build_and_tests_front
